import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/globals.css";

import { getServerSession } from "next-auth";
import Link from "next/link";
import React from "react";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">Home</Link>&nbsp;
        <Link href="/about">About</Link>&nbsp;
        <Link href="/profile">Profile</Link>&nbsp;
        {session && <Link href="/me">{session.user?.name}</Link>}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
