import AccordionHeader from "./AccordionHeader";
import Nadebox from "./Nadebox";

export default function AccordionGrid() {
  return (
    <div className="accordion-grid">
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
    </div>
  );
}
