import Nadebox from "/components/Nadebox";

export default function Content() {
  return (
    <div className="split-content">
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
      <Nadebox />
    </div>
  );
}
