export const Nades = [
    {
        zone: "outside",
        id: 112,
        type: "smoke",
        title: "Near Cross Smoke",
        origin: "t-spawn",
        land: "near cross outside",
        map: "nuke",
        side: "t",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        lineup: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_near_lineup.png",
        thumbnail: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_near_thumb.png",
        video: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_near.mp4"
    },
    {
        id: 9464,
        type: "smoke",
        zone: "outside",
        title: "Far Cross Smoke",
        origin: "t-spawn",
        land: "far cross outside",
        map: "nuke",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_far_thumb.png",
        video: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_far.mp4",
        lineup: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_far_lineup.png",
    },
    {
        id: 9465,
        type: "smoke",
        zone: "outside",
        title: "Front Mini Smoke",
        origin: "t-spawn",
        land: "front mini outside",
        map: "nuke",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        lineup: "/assets/clips/nuke/outside_smoke_t-spawn_outside_front-mini_lineup.png",
        thumbnail: "/assets/clips/nuke/outside_smoke_t-spawn_outside_front-mini_thumb.png",
        video: "/assets/clips/nuke/outside_smoke_t-spawn_outside_front-mini.mp4",
    },
    {
        id: 9466,
        type: "smoke",
        title: "Far Cross Smoke",
        zone: "outside",
        origin: "t-spawn",
        land: "close cross",
        map: "nuke",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross_thumb.png",
        video: "/assets/clips/nuke/outside_smoke_t-spawn_outside_cross.mp4"
    },
    {
        id: 9467,
        type: "molly",
        title: "Glaive Molly",
        zone: "outside",
        origin: "fence",
        land: "glaive",
        map: "nuke",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        lineup: "/assets/clips/nuke/outside_molly_fence_glaive_lineup.png",
        thumbnail: "/assets/clips/nuke/outside_molly_fence_glaive_thumb.png",
        video: "/assets/clips/nuke/outside_molly_fence_glaive.mp4"
    },
    {
        id: 9500,
        type: "smoke",
        title: "front bathrooms smoke",
        map: "overpass",
        origin: "t-spawn",
        land: "front bathrooms",
        zone: "bathrooms",
        side: "t",
        pro: true,
        technique: "jump",
        movement: "no",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/bathrooms_smoke_t-spawn_front-bathrooms_t.png",
        video: "/assets/clips/overpass/bathrooms_smoke_t-spawn_front-bathrooms.mp4"
    },
    {
        id: 9501,
        type: "flash",
        title: "b monster flash",
        map: "overpass",
        origin: "t-spawn",
        land: "monster",
        zone: "b",
        side: "t",
        pro: true,
        technique: "jump",
        movement: "yes",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/b_flash_outside-monster_monster_t.png",
        video: "/assets/clips/overpass/b_flash_outside-monster_monster.mp4"
    },
    {
        id: 9502,
        type: "flash",
        title: "water flash",
        map: "overpass",
        origin: "t-spawn",
        land: "water",
        zone: "b",
        side: "t",
        pro: true,
        technique: "jump",
        movement: "no",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/b_flash_t-spawn_short_t.png",
        video: "/assets/clips/overpass/b_flash_t-spawn_short.mp4"
    },
    {
        id: 9503,
        type: "flash",
        title: "pillar flash",
        map: "overpass",
        origin: "water",
        land: "pillar",
        zone: "b",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/b_flash_water_pillar_t.png",
        video: "/assets/clips/overpass/b_flash_water_pillar.mp4"
    },
    {
        id: 9504,
        type: "flash",
        title: "b short flash",
        map: "overpass",
        origin: "water",
        land: "b short",
        zone: "mid",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/b_flash_water_short_t.png",
        video: "/assets/clips/overpass/b_flash_water_short.mp4"
    },
    {
        id: 9505,
        type: "molly",
        title: "Barrels Molly",
        map: "overpass",
        origin: "water",
        land: "barrels",
        zone: "b",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/b_molly_water_headshot_t.png",
        video: "/assets/clips/overpass/b_molly_water_headshot.mp4"
    },
    {
        id: 9506,
        type: "molly",
        title: "Pit Molly",
        map: "overpass",
        origin: "water",
        land: "pit",
        zone: "b",
        side: "t",
        pro: true,
        technique: "stand",
        movement: "no",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/overpass/b_molly_water_pit_t.png",
        video: "/assets/clips/overpass/b_molly_water_pit.mp4"
    },
    {
        id: 0,
        type: "smoke",
        title: "z",
        origin: "outside-a",
        zone: "a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 1000,
        type: "smoke",
        title: "A Site Smoke",
        zone: "a",
        origin: "a-site",
        land: "a-site",
        map: "inferno",
        side: "ct",
        tick: "any",
        pro: true,
        technique: "crouch",
        movement: "no",
        difficulty: "easy",
        collection: "advanced",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4",
    },
    {
        id: 1,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        zone: "a",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox2.png",
        video: "/assets/clips/mirage/a_smoke_ramp_jungle.mp4"
    },
    {
        id: 2,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        zone: "a",
        side: "t",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 7,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        zone: "a",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 12,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        zone: "a",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 11275,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: false,
        zone: "a",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 111,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        zone: "a",
        tick: "any",
        pro: true,
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
];

export default Nades;