export const nade = [
    {
        id: 0,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 1000,
        title: "A Site Smoke",
        origin: "a-site",
        land: "a-site",
        map: "inferno",
        side: "ct",
        tick: "any",
        pro: "yes",
        technique: "crouch",
        movement: "no",
        difficulty: "easy",
        collection: "advanced",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 1,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox2.png"
    },
    {
        id: 2,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png"
    },
    {
        id: 3,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 4,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 5,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 6,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 7,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png"
    },
    {
        id: 8,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 9,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 10,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png"
    },
    {
        id: 11,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 12,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 111111,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 1001,
        title: "A Site Smoke",
        origin: "a-site",
        land: "a-site",
        map: "inferno",
        side: "ct",
        tick: "any",
        pro: "yes",
        technique: "crouch",
        movement: "no",
        difficulty: "easy",
        collection: "advanced",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 111,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox2.png"
    },
    {
        id: 112,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png"
    },
    {
        id: 113,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 114,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 115,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 116,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 17,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png"
    },
    {
        id: 18,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 19,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
    {
        id: 110,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png"
    },
    {
        id: 111,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png"
    },
    {
        id: 112,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        thumbnail: "/assets/clips/Nadebox.png"
    },
];

export default nade;