export const Nades = [
    {
        id: 0,
        type: "smoke",
        title: "z",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 1000,
        type: "smoke",
        title: "A Site Smoke",
        origin: "a-site",
        land: "a-site",
        map: "inferno",
        side: "ct",
        tick: "any",
        pro: "yes",
        technique: "crouch",
        movement: "no",
        difficulty: "easy",
        collection: "advanced",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4",
    },
    {
        id: 1,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox2.png",
        video: "/assets/clips/mirage/a_smoke_ramp_jungle.mp4"
    },
    {
        id: 2,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 3,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 4,
        type: "smoke",
        title: "z",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 5,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4",
    },
    {
        id: 6,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 7,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 8,
        type: "smoke",
        title: "z",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 9,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 10,
        type: "molly",
        title: "A Site Molly",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 11,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 12,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 111111,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 1001,
        type: "smoke",
        title: "A Site Smoke",
        origin: "a-site",
        land: "a-site",
        map: "inferno",
        side: "ct",
        tick: "any",
        pro: "yes",
        technique: "crouch",
        movement: "no",
        difficulty: "easy",
        collection: "advanced",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 111145,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox2.png",
        video: "/assets/clips/mirage/a_smoke_ramp_jungle.mp4"
    },
    {
        id: 11275,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 113,
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 11490,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 11580,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 116,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 17,
        type: "molly",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 18,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 19,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
    {
        id: 110,
        type: "molly",
        title: "zzzy",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_molly_arch_a-site_thumb.png",
        video: "/assets/clips/inferno/a_molly_arch_a-site.mp4"
    },
    {
        id: 111,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/inferno/a_smoke_a-site_a-site_thumbnail.png",
        video: "/assets/clips/inferno/a_smoke_a-site_a-site.mp4"
    },
    {
        id: 112,
        type: "smoke",
        title: "Stairs Smoke",
        origin: "outside-a",
        land: "stairs",
        map: "mirage",
        side: "t",
        tick: "any",
        pro: "yes",
        technique: "stand",
        movement: "no",
        difficulty: "easy",
        collection: "essential",
        alt: "temporary",
        thumbnail: "/assets/clips/Nadebox.png",
        video: "/assets/clips/mirage/a_smoke_outside-a_stairs_safezone.mp4"
    },
];

export default Nades;